export const BASE_API = "http://3.17.255.202:8009/transporter/api/v1/transporter"
export const BASE_API_USER = "http://3.17.255.202:8009/transporter/api/v1/user"
export const LOGGED_IN_STATE = "LOGGED_IN_STATE"
export const ACCESS_TOKEN = "ACCESS_TOKEN"
export const PHONE_NUMBER = "PHONE_NUMBER"